### ISSUE TITLE
Badge Alura Challenge

### ISSUE THREAD

**Issue by LucasdeFreitasp** [Matheus-Pazinati/alura-dev-challenge#1]
Olá, frontender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nessa segunda edição do Challenge de Front-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅 
 
Abraços e te vejo nos próximos Challenges!
![Badge - Github](https://user-images.githubusercontent.com/79534537/151362417-24806007-cbed-4056-b8fb-61c05dc69c90.png)

**Comment by Matheus-Pazinati** [comment]
Muito obrigado.
